// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Repo struct {
	Img        string `json:"img"`
	RepoName   string `json:"repoName"`
	RepoDesc   string `json:"repoDesc"`
	LastCommit string `json:"lastCommit"`
}
